#!/usr/bin/env python3
"""
Chunk the LÖVE API reference into symbol-addressable records.

Input format:
  tools/love2d_docs_sync.py generates a flattened text/markdown-like document
  where symbol headings look like:
    love.graphics.print

Output:
  docs/love-api/chunks.jsonl
  Each line is a JSON object:
    {
      "symbol": "love.graphics.print",
      "sectionHeading": "love.graphics.print",
      "sourceUrl": "...",
      "text": "..."
    }
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Iterable


# Symbol headings from love-api can contain:
# - `love.*` for module-level functions/callbacks (e.g. `love.graphics.printf`)
# - `TypeName:method` for type methods/constructors (e.g. `ImageData:getPixel`, `Canvas:newImageData`)
#
# We intentionally require a separator for `TypeName:*` symbols to avoid grabbing section headings
# like `Input` / `Window`.
SYMBOL_HEADING_RE = re.compile(
    r"^(?:"
    r"love\.[a-zA-Z0-9_]+(?:[.:][a-zA-Z0-9_]+)*"
    r"|"
    r"[A-Z][a-zA-Z0-9_]+(?:[.:][a-zA-Z0-9_]+)+"
    r")$"
)


def _iter_lines(path: Path) -> Iterable[str]:
    # Preserve line order deterministically; normalize to \n.
    text = path.read_text(encoding="utf-8")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    yield from text.split("\n")


def chunk_reference(reference_text_path: Path, source_url: str, min_chars: int) -> list[dict]:
    chunks: list[dict] = []
    cur_symbol: str | None = None
    cur_lines: list[str] = []

    def flush() -> None:
        nonlocal cur_symbol, cur_lines
        if cur_symbol is None:
            return
        text = "\n".join(cur_lines).strip()
        if len(text) >= min_chars:
            chunks.append(
                {
                    "symbol": cur_symbol,
                    "sectionHeading": cur_symbol,
                    "sourceUrl": source_url,
                    "text": text,
                }
            )
        cur_symbol = None
        cur_lines = []

    for raw_ln in _iter_lines(reference_text_path):
        ln = raw_ln.strip()
        if SYMBOL_HEADING_RE.match(ln):
            # New symbol section.
            flush()
            cur_symbol = ln
            cur_lines = [raw_ln]  # keep original spacing for determinism
        else:
            # Keep lines within current symbol section.
            if cur_symbol is not None:
                cur_lines.append(raw_ln)

    flush()
    return chunks


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        default="docs/love-api/LOVE_11_5_REFERENCE.md",
        help="Reference markdown/text file (generated by love2d_docs_sync.py)",
    )
    parser.add_argument("--output", default="docs/love-api/chunks.jsonl", help="Output JSONL file")
    parser.add_argument(
        "--source-url",
        default="https://love2d-community.github.io/love-api/",
        help="sourceUrl field for each chunk",
    )
    parser.add_argument("--min-chars", type=int, default=80, help="Minimum text length per chunk")
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"Input missing: {in_path}", file=sys.stderr)
        sys.exit(2)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    chunks = chunk_reference(in_path, args.source_url, args.min_chars)

    with out_path.open("w", encoding="utf-8") as f:
        for rec in chunks:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"Wrote {len(chunks)} chunks to {out_path}")


if __name__ == "__main__":
    main()

